"""Shared rendering helpers for the showcase generators. Every builder composes pages from these, so the
house style lives in exactly one place (presentation/tokens.py :: HOUSE_CSS) and can't drift. Everything
here is self-contained — no external asset links; fonts are named in the CSS and degrade gracefully.
"""
from __future__ import annotations

import html as _html

from presentation.tokens import HOUSE_CSS


def esc(x) -> str:
    return _html.escape(str(x), quote=True)


def document(title: str, kicker: str, h1: str, sub: str, body: str, back: bool = True) -> str:
    """A complete, self-contained HTML page in the house style."""
    back_link = '<a class="back" href="/hub">&larr; back to hub</a>' if back else ""
    return (
        "<!doctype html><html lang=en><head><meta charset=utf-8>"
        "<meta name=viewport content='width=device-width, initial-scale=1'>"
        f"<title>{esc(title)}</title><style>{HOUSE_CSS}</style></head><body><div class=wrap>"
        f"{back_link}"
        f"<header><div class=kicker>{esc(kicker)}</div><h1>{esc(h1)}</h1>"
        f"<div class=sub>{sub}</div></header>"
        f"{body}"
        "<div class=foot>Generated by <code>make showcase</code> from real repo data — self-contained, "
        "no external assets. Empty stops render a house-style &ldquo;pending&rdquo; card (J-02: never faked).</div>"
        "</div></body></html>"
    )


def section(num, title: str, body: str, lead: str = "") -> str:
    """A numbered `.snum` section header + body."""
    lead_html = f'<p class="lead">{lead}</p>' if lead else ""
    return (
        f'<section><div class="sh"><span class="snum">{esc(num)}</span>'
        f'<h2>{esc(title)}</h2></div>{lead_html}{body}</section>'
    )


def card(body: str) -> str:
    return f'<div class="card">{body}</div>'


def stats(pairs) -> str:
    """pairs: list of (value, label) → a row of stat chips."""
    items = "".join(f'<div class="stat"><b>{esc(v)}</b><span class="kk">{esc(k)}</span></div>' for v, k in pairs)
    return f'<div class="stats">{items}</div>'


def table(headers, rows) -> str:
    head = "".join(f"<th>{esc(h)}</th>" for h in headers)
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def pill(text: str, kind: str = "good") -> str:
    return f'<span class="pill {esc(kind)}">{esc(text)}</span>'


def cmd_block(text: str) -> str:
    return f'<pre class="cmd">{esc(text)}</pre>'


def msg_block(text: str) -> str:
    return f'<pre class="msg">{esc(text)}</pre>'


def pending(stop_title: str, needs: str, why: str = "") -> str:
    """The honest 'not yet generated' card — SAME house style, so an unfilled stop reads as intentional,
    not broken (J-02). `needs` is the exact step to fill it."""
    why_html = f"<p>{esc(why)}</p>" if why else ""
    return (
        '<div class="pending"><div class="pt">Pending — needs domain data</div>'
        f"<h3>{esc(stop_title)}</h3>"
        f"<p>This stop has no data yet. It renders from real data once you provide it — nothing is faked.</p>"
        f"{why_html}"
        f'<p class="k">To fill it:</p><pre class="msg">{esc(needs)}</pre></div>'
    )
