"""FastAPI surface. Local: uvicorn api.main:app --reload. AWS: Lambda via Mangum (deploy/template.yaml) or App Runner (deploy/Dockerfile)."""
import json
import os
import pathlib
import traceback
import uuid

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from langgraph.types import Command
from pydantic import BaseModel

from agent.graph import graph, run
from agent.state import AgentOutput

app = FastAPI(title="FDE Agent")

# Secrets Manager → env at cold start (Lambda); keeps keys out of templates and CI.
if os.getenv("ANTHROPIC_SECRET_ARN") and not os.getenv("ANTHROPIC_API_KEY"):
    try:
        import json as _j

        import boto3
        v = boto3.client("secretsmanager").get_secret_value(SecretId=os.environ["ANTHROPIC_SECRET_ARN"])["SecretString"]
        os.environ["ANTHROPIC_API_KEY"] = _j.loads(v).get("ANTHROPIC_API_KEY", v) if v.startswith("{") else v
    except Exception as e: print("secret load failed:", e)

class RunReq(BaseModel):
    task: str
    thread_id: str | None = None
    tenant: str | None = None      # D-011: caller declares tenant; server enforces

class ApproveReq(BaseModel):
    thread_id: str
    approve: bool
    hashes: list[str] = []         # D-038: the proposal_hashes the human SAW (from the interrupt payload)

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
def chat_ui():                                           # D-039: governance-visible local chat over /run + /approve
    return (pathlib.Path(__file__).parent / "chat.html").read_text()

@app.get("/health")
def health(): return {"ok": True, "provider": os.getenv("LLM_PROVIDER","anthropic"), "model_profile": os.getenv("MODEL_PROFILE"), "tenant": os.getenv("TENANT","demo")}

def _structured_500(thread_id: str, e: Exception) -> JSONResponse:
    """D-041: an unexpected exception is a STRUCTURED result, never a bare plain-text 500 — the client
    (chat UI, A2A caller, curl) always gets JSON it can render. Full traceback to the server log (J-12)."""
    traceback.print_exc()
    return JSONResponse(status_code=500, content={
        "error": type(e).__name__, "thread_id": thread_id, "detail": str(e)})

@app.post("/run", response_model=None)
def run_agent(req: RunReq):
    tid = req.thread_id or str(uuid.uuid4())
    try:
        out = run(req.task, thread_id=tid, tenant=req.tenant)
    except Exception as e:
        return _structured_500(tid, e)
    return {"thread_id": tid, **({"result": out} if "answer" in out else out)}

@app.post("/approve")
def approve(req: ApproveReq):                            # D-004 resume + D-038 approval binds to what was seen
    cfg = {"configurable": {"thread_id": req.thread_id}}
    try:
        out = graph.invoke(Command(resume={"approve": req.approve, "hashes": req.hashes}), config=cfg)
    except Exception as e:
        return _structured_500(req.thread_id, e)
    res = out.get("result")
    if res:
        from agent.graph import _trace
        res = {**res, "trace": _trace(out, req.thread_id)}
        return {"thread_id": req.thread_id, "result": res}
    # The resumed run hit ANOTHER interrupt (a further proposal, or a re-proposal after state changed) —
    # surface it exactly like /run does, never a 500: the human decides again on what they now see.
    return {"thread_id": req.thread_id, "status": "interrupted", "state": out.get("__interrupt__"), "path": out.get("path", [])}

@app.get("/trace/{thread_id}")
def get_trace(thread_id: str):                           # D-044: last run's per-layer spans for the dashboard
    from agent import telemetry
    rec = telemetry.last_run(thread_id)
    if rec is None:
        raise HTTPException(404, f"no trace for thread {thread_id}")
    return rec

_FIX = pathlib.Path(__file__).parent.parent / "evals" / "fixtures"

@app.get("/dashboard", response_class=HTMLResponse, include_in_schema=False)
def dashboard():                                         # D-044: per-layer observability dashboard
    return (pathlib.Path(__file__).parent / "dashboard.html").read_text()

@app.get("/fixtures/runs")
def fixture_runs():                                      # captured 5-scenario spans (offline demo data)
    f = _FIX / "telemetry_runs.json"
    if not f.exists(): raise HTTPException(404, "no captured runs — run scripts/capture_runs.py")
    return json.loads(f.read_text())

@app.get("/fixtures/mcp")
def fixture_mcp():                                       # measured MCP-vs-graph result
    f = _FIX / "mcp_vs_graph.json"
    if not f.exists(): raise HTTPException(404, "no bench — run scripts/bench_mcp_vs_graph.py")
    return json.loads(f.read_text())


# ---- Showcase surfaces (docs/SHOWCASE-DATA.md) — static file responses, NO logic, read-only ----
# Pages are generated by `make showcase` (python -m presentation.build_all) and are gitignored build
# outputs. A missing page NEVER dead-ends in a 404 — it returns a clean, house-style "pending" page so no
# stop breaks in front of a reviewer. demo.sh self-heals the pages on startup.
_REPO = pathlib.Path(__file__).parent.parent

def _placeholder(title: str, hint: str) -> str:
    """A self-contained, house-style 'not generated yet' page. Carries the shared tokens (Space Grotesk /
    JetBrains Mono / --structure) so a cold clone / CI serves an on-brand page and the drift test is
    hermetic — no generated file required (J-02)."""
    from presentation.tokens import HOUSE_CSS
    return (f"<!doctype html><html lang=en><head><meta charset=utf-8>"
            f"<meta name=viewport content='width=device-width, initial-scale=1'><title>{title}</title>"
            f"<style>{HOUSE_CSS}</style></head><body><div class=wrap>"
            "<a class=back href='/hub'>&larr; back to hub</a>"
            "<div class=pending><div class=pt>Pending — not generated yet</div>"
            f"<h3>{title}</h3><p>Run the generator to build this stop from real data, then refresh "
            "(<code>bash demo.sh</code> self-heals on startup):</p>"
            f"<pre class=msg>{hint}</pre></div></div></body></html>")

def _serve_html(path: pathlib.Path, hint: str):
    if not path.exists():
        return HTMLResponse(_placeholder(path.stem, hint), status_code=200)
    return HTMLResponse(path.read_text())

_PRES = _REPO / "presentation"

@app.get("/hub", response_class=HTMLResponse, include_in_schema=False)
def hub(): return _serve_html(_PRES / "index-hub.html", "make showcase")

@app.get("/business", response_class=HTMLResponse, include_in_schema=False)
def business(): return _serve_html(_PRES / "business.html", "python -m presentation.build_business")

@app.get("/problem", response_class=HTMLResponse, include_in_schema=False)
def problem(): return _serve_html(_PRES / "problem.html", "python -m presentation.build_problem")

@app.get("/audit", response_class=HTMLResponse, include_in_schema=False)
def audit(): return _serve_html(_PRES / "audit.html", "python -m presentation.build_audit")

@app.get("/infra", response_class=HTMLResponse, include_in_schema=False)
def infra(): return _serve_html(_PRES / "infra.html", "python -m presentation.build_infra")

@app.get("/evals", response_class=HTMLResponse, include_in_schema=False)
def evals(): return _serve_html(_PRES / "evals.html", "python -m presentation.build_evals")

@app.get("/deploy", response_class=HTMLResponse, include_in_schema=False)
def deploy(): return _serve_html(_PRES / "deploy.html", "python -m presentation.build_deploy")

@app.get("/a2a", response_class=HTMLResponse, include_in_schema=False)
def a2a(): return _serve_html(_PRES / "a2a.html", "python -m presentation.build_a2a")

@app.get("/signal", response_class=HTMLResponse, include_in_schema=False)
def signal(): return _serve_html(_PRES / "signal.html", "python -m presentation.build_signal")

@app.get("/data", response_class=HTMLResponse, include_in_schema=False)
def data(): return _serve_html(_PRES / "data.html", "python -m presentation.build_data")

@app.get("/runnable", response_class=HTMLResponse, include_in_schema=False)
def runnable(): return _serve_html(_PRES / "runnable.html", "python -m presentation.build_runnable")

@app.get("/workflows", response_class=HTMLResponse, include_in_schema=False)
def workflows(): return _serve_html(_PRES / "workflows.html", "python -m presentation.build_workflows")

# A2A: another agent can call POST /run and gets AgentOutput back — same contract, any language.
@app.get("/contract")
def contract(): return AgentOutput.model_json_schema()

try:
    from mangum import Mangum
    handler = Mangum(app)                                # AWS Lambda entrypoint
except ImportError:
    pass
